version: 2.1

orbs:
  go: circleci/go@2.2.4

jobs:
  build:
    executor:
      name: go/default
      tag: '1.23'
    steps:
      - checkout
      - go/with-cache:
          steps:
            - go/mod-download
            - run:
                name: Generate Command Files
                command: make generate-cmd
            - run:
                name: Format Check
                command: make fmt
            - run:
                name: Build
                command: make build
            - run: 
                name: Install
                command: make install
            
  test:
    executor:
      name: go/default
      tag: '1.23'
    steps:
      - checkout
      - go/with-cache:
          steps:
            - go/mod-download
            - go/test:
                covermode: atomic
                race: true
                verbose: true

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
