/*
Okta Admin Management

Allows customers to easily access the Okta Management APIs

API version: 5.1.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// PrivilegedResourceAccountOktaAllOfCredentials Credentials for the privileged account
type PrivilegedResourceAccountOktaAllOfCredentials struct {
	// The username associated with the privileged resource
	UserName *string `json:"userName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrivilegedResourceAccountOktaAllOfCredentials PrivilegedResourceAccountOktaAllOfCredentials

// NewPrivilegedResourceAccountOktaAllOfCredentials instantiates a new PrivilegedResourceAccountOktaAllOfCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivilegedResourceAccountOktaAllOfCredentials() *PrivilegedResourceAccountOktaAllOfCredentials {
	this := PrivilegedResourceAccountOktaAllOfCredentials{}
	return &this
}

// NewPrivilegedResourceAccountOktaAllOfCredentialsWithDefaults instantiates a new PrivilegedResourceAccountOktaAllOfCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivilegedResourceAccountOktaAllOfCredentialsWithDefaults() *PrivilegedResourceAccountOktaAllOfCredentials {
	this := PrivilegedResourceAccountOktaAllOfCredentials{}
	return &this
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *PrivilegedResourceAccountOktaAllOfCredentials) GetUserName() string {
	if o == nil || o.UserName == nil {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivilegedResourceAccountOktaAllOfCredentials) GetUserNameOk() (*string, bool) {
	if o == nil || o.UserName == nil {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *PrivilegedResourceAccountOktaAllOfCredentials) HasUserName() bool {
	if o != nil && o.UserName != nil {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *PrivilegedResourceAccountOktaAllOfCredentials) SetUserName(v string) {
	o.UserName = &v
}

func (o PrivilegedResourceAccountOktaAllOfCredentials) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserName != nil {
		toSerialize["userName"] = o.UserName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PrivilegedResourceAccountOktaAllOfCredentials) UnmarshalJSON(bytes []byte) (err error) {
	varPrivilegedResourceAccountOktaAllOfCredentials := _PrivilegedResourceAccountOktaAllOfCredentials{}

	err = json.Unmarshal(bytes, &varPrivilegedResourceAccountOktaAllOfCredentials)
	if err == nil {
		*o = PrivilegedResourceAccountOktaAllOfCredentials(varPrivilegedResourceAccountOktaAllOfCredentials)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "userName")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullablePrivilegedResourceAccountOktaAllOfCredentials struct {
	value *PrivilegedResourceAccountOktaAllOfCredentials
	isSet bool
}

func (v NullablePrivilegedResourceAccountOktaAllOfCredentials) Get() *PrivilegedResourceAccountOktaAllOfCredentials {
	return v.value
}

func (v *NullablePrivilegedResourceAccountOktaAllOfCredentials) Set(val *PrivilegedResourceAccountOktaAllOfCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivilegedResourceAccountOktaAllOfCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivilegedResourceAccountOktaAllOfCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivilegedResourceAccountOktaAllOfCredentials(val *PrivilegedResourceAccountOktaAllOfCredentials) *NullablePrivilegedResourceAccountOktaAllOfCredentials {
	return &NullablePrivilegedResourceAccountOktaAllOfCredentials{value: val, isSet: true}
}

func (v NullablePrivilegedResourceAccountOktaAllOfCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivilegedResourceAccountOktaAllOfCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

